#!/usr/bin/env python3
"""Bake a Bay Area land/water layer for the scope-app area map.

Reads Natural Earth 10m LAND polygons (public domain,
tools/ne-data/ne_10m_land.geojson), clips them to the Bay Area window,
simplifies, and writes src/lib/coastdata.ts - the land rings in lon/lat
degrees. The map paints a WATER background, then the land polygons on
top; the Bay itself appears naturally as the gap at the Golden Gate.
(An ocean-polygon source was tried first and failed: its interior
covers the whole window, so clipping it yields a full water rectangle.)

Re-run only when the coastline data changes:
    python tools/bake_coast.py
"""
from __future__ import annotations

import json
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
SRC = APP / "tools/ne-data/ne_10m_land.geojson"
OUT = APP / "src/lib/coastdata.ts"

# Bay Area window (covers the 94945 demo grid with margin; the host's
# area square will always be INSIDE this, so the clip never bites a
# real layout).
BBOX_W, BBOX_S, BBOX_E, BBOX_N = -123.2, 37.4, -121.9, 38.4
# Douglas-Peucker tolerance in degrees (~150 m at this latitude).
TOLERANCE = 0.0015


def point_line_dist(p, a, b):
    (px, py), (ax, ay), (bx, by) = p, a, b
    dx, dy = bx - ax, by - ay
    if dx == dy == 0:
        return ((px - ax) ** 2 + (py - ay) ** 2) ** 0.5
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    cx, cy = ax + t * dx, ay + t * dy
    return ((px - cx) ** 2 + (py - cy) ** 2) ** 0.5


def simplify(coords, tol):
    # Iterative Douglas-Peucker (no recursion limits).
    if len(coords) < 3:
        return coords
    keep = [False] * len(coords)
    keep[0] = keep[-1] = True
    stack = [(0, len(coords) - 1)]
    while stack:
        lo, hi = stack.pop()
        if hi <= lo + 1:
            continue
        dmax, idx = -1.0, -1
        for i in range(lo + 1, hi):
            d = point_line_dist(coords[i], coords[lo], coords[hi])
            if d > dmax:
                dmax, idx = d, i
        if dmax > tol:
            keep[idx] = True
            stack.append((lo, idx))
            stack.append((idx, hi))
    return [c for c, k in zip(coords, keep) if k]


def clip_ring_to_bbox(ring):
    """Sutherland-Hodgman polygon clip against the bbox rectangle."""
    def clip_edge(pts, inside, intersect):
        out = []
        for i, cur in enumerate(pts):
            prev = pts[i - 1]
            if inside(cur):
                if not inside(prev):
                    out.append(intersect(prev, cur))
                out.append(cur)
            elif inside(prev):
                out.append(intersect(prev, cur))
        return out

    def ix_x(pts, x):
        return lambda a, b: (x, a[1] + (b[1] - a[1]) * (x - a[0]) / (b[0] - a[0]))

    def ix_y(pts, y):
        return lambda a, b: (a[0] + (b[0] - a[0]) * (y - a[1]) / (b[1] - a[1]), y)

    pts = ring
    pts = clip_edge(pts, lambda p: p[0] >= BBOX_W, ix_x(pts, BBOX_W))
    pts = clip_edge(pts, lambda p: p[0] <= BBOX_E, ix_x(pts, BBOX_E))
    pts = clip_edge(pts, lambda p: p[1] >= BBOX_S, ix_y(pts, BBOX_S))
    pts = clip_edge(pts, lambda p: p[1] <= BBOX_N, ix_y(pts, BBOX_N))
    return pts


def ring_area(ring):
    s = 0.0
    for i in range(1, len(ring)):
        (x0, y0), (x1, y1) = ring[i - 1], ring[i]
        s += x0 * y1 - x1 * y0
    return abs(s) / 2


def main():
    gj = json.loads(SRC.read_text())
    polys = []
    for feat in gj["features"]:
        geom = feat["geometry"]
        if geom["type"] == "Polygon":
            parts = [geom["coordinates"]]
        elif geom["type"] == "MultiPolygon":
            parts = geom["coordinates"]
        else:
            continue
        for poly in parts:
            # LAND polygons: outer ring is the land body. Clip, then
            # keep rings that survive with real area.
            ring = clip_ring_to_bbox(poly[0])
            if len(ring) < 4:
                continue
            ring = simplify(ring, TOLERANCE)
            if len(ring) >= 4 and ring_area(ring) > 0.0005:
                polys.append([[round(x, 5), round(y, 5)] for x, y in ring])

    total_pts = sum(len(p) for p in polys)
    body = json.dumps(polys, separators=(",", ":"))
    ts = f"""/**
 * BAKED Bay Area coastline - DO NOT EDIT BY HAND.
 *
 * Generated by tools/bake_coast.py from Natural Earth 10m LAND
 * polygons (public domain). LAND rings in plain lon/lat degrees,
 * clipped to the Bay Area window and simplified (~150 m tolerance).
 * The map paints water as its background and these land polygons on
 * top (lib/areamap.ts); no libraries, no network at runtime.
 *
 * {len(polys)} polygon(s), {total_pts} points.
 */
export const COAST_BBOX = {{
  west: {BBOX_W}, south: {BBOX_S}, east: {BBOX_E}, north: {BBOX_N},
}} as const;

export type CoastRing = [number, number][];

export const LAND_RINGS: CoastRing[] = {body};
"""
    OUT.write_text(ts)
    print(f"wrote {OUT.name}: {len(polys)} rings, {total_pts} points, "
          f"{len(body) / 1024:.0f} KB")


if __name__ == "__main__":
    main()
